// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caffxrhxnzurxpivokxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhZmZ4cmh4bnp1cnhwaXZva3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzY1OTYsImV4cCI6MjA2NTU1MjU5Nn0.go7mpzxupgWJe_XunFZE4PBMarYligm_EdVLhHfj9Ao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);